### ISSUE TITLE
Project Restructure [PART - 2]

### ISSUE THREAD

**Issue by anik3tra0** [syook/react-tabulous#13]
- [ ] Move all `.js` files except `index.js` to `/src/utils/`
- [ ] Test your changes

**Comment by KshitijMhatre** [comment]
I would like to take this up and [part1] please. Thanks!

**Comment by anik3tra0** [comment]
Sure. Kshitij. Take it up. Looking forward to your PR.

**Comment by KshitijMhatre** [comment]
Hi, @anik3tra0 I did all the refactoring and the build is generated successfully. But when I tried to test it;
I created a new react app and put the generated build in src. When I tried to import the table it's showing errors. 
adding `/* eslint-disable no-unused-expressions */` to top of the build removed majority of expected assignment or function errors. 
but it's still won't let me build with these errors,
```
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/syook-table.min.js
  Line 12:44293:   Unexpected use of 'self'                         no-restricted-globals
  Line 12:44299:   Unexpected use of 'self'                         no-restricted-globals
  Line 12:44305:   Unexpected use of 'self'                         no-restricted-globals
  Line 12:44327:   Unexpected use of 'self'                         no-restricted-globals
  Line 25:14428:   'MSApp' is not defined                           no-undef
  Line 25:14476:   'MSApp' is not defined                           no-undef
  Line 25:117172:  '__REACT_DEVTOOLS_GLOBAL_HOOK__' is not defined  no-undef
  Line 25:118040:  '__REACT_DEVTOOLS_GLOBAL_HOOK__' is not defined  no-undef
  Line 25:118087:  '__REACT_DEVTOOLS_GLOBAL_HOOK__' is not defined  no-undef

Search for the keywords to learn more about each error.
```

**Comment by anik3tra0** [comment]
Hey Kshitij, thanks for reporting this. We are looking into this. Will post an update soon.
