### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by anik3tra0** [syook/react-tabulous#6]
Need to setup test suite and enable CI
- [x] Setup Test Suite 👉 https://reactjs.org/docs/test-utils.html
- [x] Add & Configure TravisCI

**Comment by nandhae** [comment]
can you be more specific about it and the files? @anik3tra0

**Comment by anik3tra0** [comment]
@nandhae yes. I am just adding more details to each issue as I am listing them. For now I have put this on hold as #2 needs to be merged.
