### ISSUE TITLE
Unable to push to the branch (table-column-resizable) I created.

### ISSUE THREAD

**Issue by AmeySyook** [syook/react-tabulous#94]
remote: error: GH006: Protected branch update failed for refs/heads/table-column-resizable.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:syook/react-tabulous.git
 ! [remote rejected] table-column-resizable -> table-column-resizable (protected branch hook declined)
error: failed to push some refs to 'github.com:syook/react-tabulous.git'

**Comment by amanthegreatone** [comment]
try again. added user profile with write access

**Comment by AmeySyook** [comment]
> try again. added user profile with write access

Oh cool. Just noticed the reply. Will try pushing again. Thanks.
